"""fix items table schema

Revision ID: f428361a56b6
Revises: 
Create Date: 2025-09-04 21:45:14.000591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f428361a56b6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('ext_id', sa.String(), nullable=True))
    op.add_column('items', sa.Column('source_handle', sa.String(), nullable=True))
    op.add_column('items', sa.Column('lat', sa.Float(), nullable=True))
    op.add_column('items', sa.Column('lon', sa.Float(), nullable=True))
    op.add_column('items', sa.Column('media_url', sa.String(), nullable=True))
    op.add_column('items', sa.Column('raw_json', sa.JSON(), nullable=True))
    op.alter_column('items', 'id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('items', 'text',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_unique_constraint('uq_ext_source', 'items', ['ext_id', 'source'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_ext_source', 'items', type_='unique')
    op.alter_column('items', 'text',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('items', 'id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('items', 'raw_json')
    op.drop_column('items', 'media_url')
    op.drop_column('items', 'lon')
    op.drop_column('items', 'lat')
    op.drop_column('items', 'source_handle')
    op.drop_column('items', 'ext_id')
    # ### end Alembic commands ###
